# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('department', models.CharField(max_length=45)),
                ('program', models.CharField(max_length=45)),
                ('url', models.URLField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jobtitle', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
