# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='latitude',
            field=models.FloatField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='longitude',
            field=models.FloatField(max_length=150, null=True),
        ),
    ]
