# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 01:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_recommendation', '0003_auto_20170430_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='jobtitle',
            new_name='Jobtitle',
        ),
    ]
