# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_recommendation', '0006_jobs_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=20)),
                ('number', models.IntegerField(max_length=15)),
            ],
        ),
    ]
