# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_recommendation', '0007_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='number',
            field=models.IntegerField(),
        ),
    ]
