# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_recommendation', '0008_auto_20170501_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
