# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_recommendation', '0009_auto_20170501_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='domain',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='url',
            field=models.URLField(max_length=100),
        ),
    ]
