# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_recommendation', '0012_auto_20170507_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='domain',
            field=models.CharField(default=b'Others', max_length=100, null=True),
        ),
    ]
