# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_recommendation', '0013_auto_20170507_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='domain',
            field=models.CharField(default=b'Others', max_length=100),
        ),
    ]
