# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_recommendation', '0014_auto_20170507_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
